apiVersion: batch/v1
kind: Job
metadata:
  name: docker-example
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: docker-example
          image: vitcozzolino/mlflow-docker-example
          command: ["python train.py --alpha 0.5"]
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      restartPolicy: Never
