apiVersion: batch/v1
kind: Job
metadata:
  name: docker-example
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: docker-example
          image: mlflow-docker-example
          command: ["python train.py --alpha {alpha} --l1-ratio {l1_ratio}"]
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      restartPolicy: Never
