apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /argocd(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server.argocd.svc.cluster.local
                port:
                  number: 80
          - path: /minio/(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: minio-service.minio.svc.cluster.local
                port:
                  number: 80
