{{- if .Values.auth.enabled -}}
{{- $databaseUri := "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-config-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{ default "basic_auth.ini" (.Values.auth.configFile | trimPrefix "/") }}: |-
    [mlflow]
    default_permission = {{ .Values.auth.defaultPermission }}
  {{- if .Values.auth.postgres.enabled }}
    {{- $dbConnectionDriver := "" }}
    {{- if .Values.auth.postgres.driver }}
      {{- $dbConnectionDriver = printf "+%s" .Values.auth.postgres.driver }}
    {{- end }}
    {{- $pgUser := required "auth.postgres.user must be specified" .Values.auth.postgres.user }}
    {{- $pgPassword := required "auth.postgres.password must be specified" .Values.auth.postgres.password }}
    {{- $pgHost := required "auth.postgres.host must be specified" .Values.auth.postgres.host }}
    {{- $pgPort := required "auth.postgres.port must be specified" .Values.auth.postgres.port | toString }}
    {{- $pgDatabase := required "auth.postgres.database must be specified" .Values.auth.postgres.database }}
    {{- $databaseUri = printf "postgresql%s://%s:%s@%s:%s/%s" $dbConnectionDriver $pgUser $pgPassword $pgHost $pgPort $pgDatabase }}
  {{- else }}
    {{- $sqliteFile := .Values.auth.sqliteFile }}
    {{- if .Values.auth.sqliteFullPath }}
      {{- $path := printf "%s/" .Values.auth.sqliteFullPath | trimSuffix "/" }}
      {{- $databaseUri = printf "sqlite:///%s%s" $path $sqliteFile }}
    {{- else }}
      {{- $databaseUri = printf "sqlite:///%s" $sqliteFile }}
    {{- end }}
  {{- end }}
    database_uri = {{ $databaseUri }}
    admin_username = {{ required "auth.adminUsername must be specified" .Values.auth.adminUsername }}
    admin_password = {{ required "auth.adminPassword must be specified" .Values.auth.adminPassword }}
    authorization_function = {{ required "auth.authorizationFunction can not be empty!" .Values.auth.authorizationFunction }}
{{- else if .Values.ldapAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-config-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  ldap_basic_auth.ini: |-
    [mlflow]
    default_permission = READ
    database_uri = sqlite:///ldap_basic_auth.db
    admin_username = fakeuser
    admin_password = fakepassword
    authorization_function = mlflowstack.auth.ldap:authenticate_request_basic_auth
{{- end }}
