name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Or your main development branch

env:
  DOCKERFILE_PATH: mlflow_docker_example/Dockerfile # Adjust if your Dockerfile is in a different location
  IMAGE_NAME: vitcozzolino/mlflow-docker-example # Replace with your Docker Hub username and image name
  DOCKER_REGISTRY: docker.io # Or your specific registry URL (e.g., ghcr.io)
  TAG: ${{ github.sha }} # Use the commit SHA as the default tag

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Ensure you have this secret configured in GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Ensure you have this secret configured in GitHub

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}, ${{ env.IMAGE_NAME }}:latest # Push with commit SHA and 'latest' tags

  # Optional: Deploy to Kubernetes (Example - Adapt to your deployment strategy)
  # deploy:
  #   name: Deploy to Kubernetes
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'v1.26.0' # Or your desired kubectl version

  #     - name: Apply Kubernetes manifest
  #       run: |
  #         kubectl apply -f your-deployment.yaml -n your-namespace
  #         kubectl rollout restart deployment/your-deployment-name -n your-namespace
  #       env:
  #         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }} # Ensure you have your kubeconfig as a secret
